apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis-operator
  namespace: argo-cd
spec:
  destinations:
  - name: in-cluster
    namespace: redis-operator
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  sourceRepos:
  - {{ .Values.repoUrl }} # git repository
