---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-chirpstack
  namespace: postgres
spec:
  encryptedData:
    password: AgAyodrPnXy6i5F8v45hCw1stDYZSg3B8JU7xuwbv0cAYT4TO2pyvsjxXtprBUL5eqfnS15nFnY80uOkts5d7EPgeXeSl1EUJIb6Q/vHaf/gvGv50aWMeC7S/DljJ2Ba/nJb5rsuk9t4cAK3STAb6CQN/CbhPzWUC6sj7HJ/hhy4wk8O9mjnkuxwea6Yx6Lu8ltXqWWcqEBs4TsKXWEdETf8f8zlRxymesy4pyhquNaMWENHpCJkbruY+GucXDhbVEtmbrFCKcZIBHUjEbeSRBmhP/DPahCcsOik3KjBEM7uJLOm74x/sDu02ygdez73oiD5ymeixE1Y32Ma+YTYUOcNuxZq6bjPIM/xJNDY5d8aLKoWs+D5Nfg7x0y9kP3iyPLxAOLTmUEgCdjoqmtb9BpL4oOO5zMtPWbkD3VNY6t8D9NyEsoW73OFYrlZEjg64Zmf9qOW9vA/UpwRwTi7ixGvRjpl6eY7imQAhsuVwQVNKCThhGuRWiGInONnbnFjBzuH6D0W1uJ1tRAFv8X8uVAa1Ly0fxfEcnyD0X8HgLb3EApTtDxr+hMJsYL5IBPZtFMejzt2YllZnXaDM8HdOlMe+nLYFAMWG3DFmn6Xu/PI+SSmQtr7pH2a1HWTcrm4fTUxNfN2EBpzawnr/gp+Qn2hAMh/YaiscJP1iIFXvV4eROGdp5LGqHYcDzHV169dW3v2FqliMaMj+vGw74bOdviJlLFZ7tSJOdVxxdpqbYSmpQ==
    username: AgDcTeSz9QEmWhWe/b8YqMUvp4VbIPC+eXBHjWbakPhPS/lczUB630+bBisWyAZXzaAX4TYpI0Qr0Dw6CdkGFinevNMak5er5fMtPbZ8tcef9SBuPLVKrdyj5QpEl6pUj1SNhOgxaKx64fIU5xLhb3B1ZOShH7LNrxqF+F3czOv3BmHnsrSbiUM32E3JcV5JUc/C4Y6/eyIR0LBpajQUnJAQA+Fb57Bx2k/lZW+XFul4UvJ1+U+CaOWUAw/Bm/ZIY0wazv92tHygJpu7SM4WvkrxIOLknZYwj4AZlocHhQQqZ3GDjoaWEMtI6A5NekK3xYi6fJ2ZT7M5n1yvjBzFf7mQW02gSyQbB1syLPX9QQE/5F1kzsAIPWqrLdEOCoYmadW6USw90+TvSEDbO3kLIyTjtN572eqhNP1sV8mJJKOeVqFtMF6sQNL/uJdknQzfsOQRYXYGUsh6CXaHPQAkmN6yDmMtxm3RBkVMFINfeOBU9TJddgYAupfLzckbZfJjx93F3OygGbk9lz7nhlKQlAyR778+KMkeC9RJCSuIO+YyMGnwS/deSjN1DttZHadNo8gaIHCTm5YxlcmlUoBawBr6z7MJhVLKKnCfnsYW5gALCpC8wthuIBOreIOLYyTDse1jCLilEvMd+DmoRurAEnp1F3D+liX5McBkJyeIKjio+BfUb8CEwbtjIrcI1X+1lhQMgYkcmYoFuIan
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-chirpstack
      namespace: postgres
    type: Opaque
