---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-chirpstack
  namespace: postgres
spec:
  encryptedData:
    password: AgAIBaYyZjzY0ivS2ApNxvnR/JvKWDrKnGbwvcnkwK4S8xLNsnrpzJXgksku75EL7te6BOeuhMpMSrPVyHQ32AwCOFxWDYY0H92Zi015KF01MXAjx4XJl73JrfuYZQtaNYBcGA8eHa+ueBcR3Fbf/viVZm1T0X0I+nXh5hETrOAmAH86HGhdRRcVkxfuyXYoLwsCz1lnAXrwZ3GXMkIvcddcmtsospGKI1tCFS7kTByodJCsy1mXMklA3ZYexUcol2TlVDNWvq6E+TBteznLWkLkPubm8JD6PA/5liYU6QCpPP6PfSz90c9ElO8iNmY8DiFE9AOvKUlCcfKARXnUgT1vpVj1b64nKq5m3ZF8XYPkEHXcOXhQfGJoHp3ocWooy5QhWydKXR73WUsatXNNCRor9HwVmDvAbFQqWzqf14coVD26vQRxPDRQs/Y5lAh7lKJ6cokR41SQwH+pAtB7xCxLYQ/Gd4EyJ955TWm0ElkHsqfj1O86XeQv7AQLfIBOsNAEs6qPbQbq4JkqjaAPLCbsptCVNwIUngB3Zr47yLHEeSnVZ0oouulCjh5I3QOyPEqNC2Kp/qyl6HadvelYp/sBDyu2qTj3lyo+RhYanPB+KFoaO80TNAQ9DeIE9ffoEeHRNOQLBUJi9yI5oG3m0hGHsgGKeFsJcv4U/kkhtG0JFlobxs30U9cV98BmkYhfVk2qJpLMLWYA+oDFLe8S6q4AWL1j3nOUKmuOK4uWA09Csg==
    username: AgCzey44U7Z3bQ7kC/Q92ajubZrpPZVC3r7n8DqK1M42a+A/Wr33LtCzkjuxIcPkjfwf1iz/EtKlQWIl4wL3nM0yvp8GH59QklJVhuJW6o7FK8ITA4EwySolNJ1wTKuYP/t8+/yzykAhQiOEVKBZrZn2r39LqHXUHjENAJOTLWPtthaW3mc6dpPJzbL+Mdp/ZC1Kb7RShxo2MEIqhWl5kTSXN0wBg8SKbpttAsIal6z6C0Uk82SkI6UB5hvMHTW6Cy+89u1PM+Xta3/0ZXe7nSUTGlKr1mGBQh6J3FHiNIDjrO+qXacSAXRfBN3qZtktqENkHs/AYc9FxOT5uR3PZQO+jHHzcL4Sf/f32j3usPOnY1xtZO1aEspBU9Ao1nYM/0C0oj5FaxGKajJBrT4VVF+L2Md7fBAAk41n9dghShBJAmGRaezapsSiHpdz37DmBSbOuhhBZlXlbeH3DB5nQVWmYPnhUQP7aAUOEUGatvuPbFTK03+inoEnKJb7ijVklqRNXDYdwSI0YXpql0j3Lmsicd6AnEg1iAvF0tB0EUrK60PthtJap612A/2KoJFexvFV1gffibSRCL8Z2w31oDSCrLy4ND2TFtq2cFqcEX04hFcEppAoF8T+jsAxj8eHYfqN1ow8z9TQ4nxa6ikEVAL7KxU6hfNXIkrMR2KrnMbLGzeddp0BcHv/5Mg9xa+/s813PCrSJubkDF5a
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-chirpstack
      namespace: postgres
    type: Opaque
