---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-chirpstack
  namespace: postgres
spec:
  encryptedData:
    password: AgBdhXhuQgw5+f+zHwqyCxNeItGH3EmdXnEjkZVrB14+kzP9gHa34YoneVTYMHL+/eBfx92yXs06OcIuKairbnnOfUPpchYRPa62tlNl4AnKYWFA5w74qfmkOwx1eFrZY1vL8EixXfsP+HnDIDuAHFyiOu1Q7W0QByzyGZANqdfqxXbsicM9xc7Fx7raLfcuivvNHl9ssK2raQKwlEZ+L9aCwKBmoR86zcN3gBlufRSUVDg5bSnyWAPtKjzXyTsXOaBd5FJ1tqlcN/UBIxmDJ8K6vsyDwhy4MOhODFj2/Bf1K3b7Z9THpFnIj8cnhOEVK4PpfUjTARJenWYD07jdN4FBfru1GqhIlZOy6AfV1LfvcQCvySimuBpwCaRvtsfzp3o8tFXjc6uh7oNJUVq8c/LslcbI56CI3X+dWMk8nR9l4FvNMLrvLbEz/yhbX3uNYFBlJHLfhmjSodxkTTdx0wUDCRlG8gO+j8pE5hTpY293CibQo3OjCU8YcPWV3ihh/1iI4oejOXx3MczsqDsEJehz4CtMjxwe9NFQfLC4jXanAZn9ALMDbCYZUN4WVr5FKCO+owKEr2vJOc8ul362LCzwohZxPCUqq5xwYMSXYgezcy1FyH5LSHrXb9tqlQJfybNk67r3MZx/uZCO3TxYCDMNcjlj0/iHJ0YAyGY+/LHZuJjMrKG+JiUWFoD6oFw2v/oJd3SCX1C5nXY7ufAnUzhNLBN+wwRDPUzLo6HaLl4k7A==
    username: AgBJPiHtvar16dIgGKhhn1lw9DvbJXaHT7WmCRB3d8HlcyxYs0/rMuC0AVGfG7TZJHHbOSz91WW2314e/9dYXpYznWdZfEm7C1JYV5ux/kWg7eB+yVc9y1+IRv36IyX66DLEFigcN++GEhUr0jOx3Zp5XXmIyQNvaVDDoEgA2qtuepJ/doy1WN1BeVEX8X2v3SLgHzZBWpdb5MrO10OrhJwyYTLk2tpjnbWdSe/zLaYSGJZPPoaLK0vnopm2ZZa7A2wI9MgJf5oIbtLzoThKmAbBJXozg4/iUEHT1tXipT74h3ClvGwv7Cjfm/sqgLOmCOcKXYSnSBgQTJIxKOjkypfAKEsG1lEhvdizvuM76WO8z7LJ1qUNyHK/nFI+BJWaHrhzQEG30xiQW6/BWz1loUzMr5JsFyCdzz3PBqo1R9vHju/9bNjEtN3Phtwdi9EaLHrOsk0u/FuzbWLcTeW35xSOAZq5mvsZ2H44mjHJnVPPIeXycW85RJa6c4WYbXKYPMSO8Xv97+/BVjj9HWJGEPoMZ/nIX2y1oL5gtPDmLuzUaDs2T4EPCSeHybaxmoFqHIbzBa9dANoIbq5LUwj/U+3JsZOVa9Ar6wQZmuQuIc35OMT6ugdA4xV9qvmp8Zva1PyE/qgoCc0V3xKLZn4F56Hz8yiPQLIq+PUu9Y9YNMx+TFdIdFmkdc6mVhO29KcK8356HKL+Q+mgSyb6
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-chirpstack
      namespace: postgres
    type: Opaque
