---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-chirpstack
  namespace: postgres
spec:
  encryptedData:
    password: AgAsuAnLuD2nxByOhCQKmkjyT99GlHOatifUeTBpTQ/xWjc9H+Ci8lPCaK04/gyCyAVQvp3lA6cYClCJX8DcYwCcaabW/zEMO6wa719EZ7HMxobLdEm4CmU6W5vyPZW38J3sn+sfihFwy1CgqVGspBPGO9EGQkgG/q1cZH2bCqCbMALqMx6vcqy/n6k3YCJZ+EdnepzKq6CwojD42hEtoQu9T68uOAMPFrUhbLmv2QkedZkPZF+JdzuQXKCPGihF6BQ3OGTlUZ+CfbElDNrv7GNGtebieabJwJiFbGZeCXwxug9V83Z8JC25S+o/G/NvbaJTvolKcKEKxae+PUd5++Os1XbAw0x3pt2sTv5lNbyel/C0d2OGaRz/SafnhE4rliGe2S1Lf7p0fGG+INxSbQEfLxnovzLcFDuxPAgbFM6PQ8GAo4pk4FArXnE7qE9Oh9IH+JCX0vDncYu2tNy2FL1pbs/mfXnQu87gYjkgeMc6sqBes2ofLzIeR+TCGDYQt7OxRh+5LIrgn4uuiumOGmeu/8wRIjeBzRKz8BUyWtI9HgDaaly0rxeaMNXhfDyVw12JGyFbTjsospAjJc//jCH+YFkN0htOzv3pWvizTeMhkmdqpcekUJhxrjdNIanqSeiIvoK32r7A47iHWrsxiJ1KnWn+8aK5Jjz63aIYaA4zuQGX0JiGa1uhsaK9Om4bRQUz/TzCqmlUv/jWqWq9cJiwBzQUz9HcqZg/TV4TEaP3hQ==
    username: AgCZhYFQxxa7S/sFAeqhs1tsznG5pDWmHB8jxE4HolyfPwR36HGpyX+Dash+WibV0IVfNYE0C7GqhghKSscHNQIujCEUcJXscFfA4cywak4DIUTTjgZmojGw+9sR8eJwhzEiVbatLPsjDi/Kkmi0KvPGwz4zdHsgTcC6drbCsz0AgOEh5aStU389ji1VBbIWv4Nxezxx6+5WfV68K11ngRQf5AnOfJPCIovM65mdKAHxP1E30Mt8mS2Vwvp4+XEyjlXS6fUFYUK/YtsqoCgcJRR49rdBIiA4UB7wDdwHN/yUJKXc252umPLrBSzS7zJ9sSfeq27q9inObWDh2WVhRKeyWzcM8nIqYQD3xv080MiZhqR+xNB26KPDTKAET0i1FxDRAGzxMWEcxjH0YBP5rnRLO14oMarP1DJrYsJO86344SBeqnxepBL9twAQ1lNpeor8JQY6xEYzdSpRSk2dD9/Oh6Qv4EKGCcFL3imc1jrD9ascB6v5BaorUycVLOrm4Ri6qwhWlBlICLL3CU8QzcRcKzUiLmp1ETL7jsX2pMLc+IsCXU8MvAbElFnFJEc2u4rPIGSh6Mg8YY3Ctgr9WpNYKLpdsxmlN7/kqPkwwSDeEaAGcSW5NBWc/XUd82r0Dwm5RYaUfC4uuVsH+cXZ3x6K8aeDCAyTjGASRftbOs1QD7Q0ow+R0sIDuDX6uQt6S6lR8fRl8pe2u+vw
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-chirpstack
      namespace: postgres
    type: Opaque
