---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-os2iot
  namespace: postgres
spec:
  encryptedData:
    password: AgBvhHLR5WeD0WPYQfBD9OWS8lrzus+/TPd9LqWOBEU5Aqplcuw5bIzSNmQ0C/y+FLh+nCTUMSPMo/GDBEvbug7HzuahK8fjITOi8sLSj4ZBd0OkfI/0HChzmh/d00sJqc98QBA7jOIEt5cx5trAAABNPlS9QvyVjtimQzS07gzjSyJN658R7RO+MFt/4b5hlQdWZK7M/Hzs+ZQrKptXOcw5NUyH7X1Sayx2lrqIXRbVczCVihSaN+4bwNn4creaMkkkT621/KDwyzLiaimnaUcbLu2vCDuURAdF+XQb2f/83iiUz3CQlFZ4woIHtw6CjqZVEaKiCay8A2bcUiBV0vLy0xmhNzDVaHnyC4pjKopF8HLeqSJkyQk1blvv0lphpmiw+rz1sn8gy8TyBj6ACIxzRUNo4A+7WiJfFU1uJMOk2sgQQrVppoXvTjRIyWrUpGyNR4mmsDjkhOGdOFh+9JGsQKFuNuydt4V1uraQ3XvtGxrUSaxIDOhSWeuWBjcFJSkDrG8iXKjYMhuP1sn43Pq9DxTp0W5lmRZM4OikvHXqYBRKO9YtVV7t4DBsIdZNDmF2xINfxqnCk06aX700UBXoW6NsNPkoTbPIBYpxPJzyBkC6+6BbDxuHxgFhmd6IFxhXuqjagK9MGkKkbeeMdl1sIThftvwgcLBg+VpT1/rROvGhvxagMbQSDbGUmcPSKxTcS0bbNlUd0tPa/o7OizBwG1fkKtqC2pjEII+6s0mMRQ==
    username: AgAq3SaIpn/AWV/REWVlSEB7OSNjvBmL1U8LuKl4hrzA0X9PM290TSDLAWjxObgmSIBBDccYcWYqtBvYNMs+99KcKonEoNE0f3w6S7/T3ZQ6MSa14nKCLtZs/OU5XLzybwnq+/WOynSphNxh1/vwsnyXpozn5QTmrSbkl0eXpBKf/GrrSP0qaImHlQfU0VFgC2xZshQAAjTZ3OKf3nT3anqnwNtAdax66kYHO8R88nDGa3mNFVGWOCm5cAfinR8M81B5rLyLE2s4qWgHrGGHg42CjwBCfbqJ/Yocu7Eyst5HRsWbb2ZZ2e/kyUYolhgfregppmYqPogiWphCBcWjzx5o6goJSnFmGBTcLx/GK45Y35wLANK2pgmbCJF/6UR403o/2n2xsEbDRXZpCTY6X++VKmuphzcdsyGjZyVydhRK70KS1Br8ZmG1PJaEGfSUPpaLGxBkRwUWy0cZVHtXQ5Tt8tOl7QLL+IOwejzmQ2flwZH2t7zbQsXBuK0E44f40S9NAMP8bI2jbHFCHUW9VjnX+z5Jaiy7fGxvJunD25LFv1AVqL+dHGbiEzz1dl5jAab8IJzrVRIRNQ1VOY+do+L+OP5UN9uJewH4X3n7VNA8qH6vu1IHWcL494pHuiTjOhLX5wf49YuGoGRAW7t8qNlzeTCNbRbojlOR0sIbiWTtu1/bNo1IU4eNn7UfXqfKQkQvcn5+zd8=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-os2iot
      namespace: postgres
    type: Opaque
