---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: os2iot-backend-encryption
  namespace: os2iot-backend
spec:
  encryptedData:
    symmetricKey: AgAbjnzZc2Jby/B0fpD48YY3i4qf7Vgcm3I2U98/RMq7oTGoXPEP2fEG0ueuVwbsKvbomWCCa7GMdrxKRfh0vAZPvxdAqaEx9reuRgjeCexPdPxGEaAokmHL+x6p31mqw3t8w0e9X4918thQLv+NNv5jS+6xkboGPBZ3uVtu4+9z5cUKoScerty4dedd+5aJI/ELMuB1AH7A0foXI9PqM7qPzofKEh0LzQGkaFa4lj0Owa+kUqdmKP81DJjti0XZ1lf8Uqiu1G5xyO/YXUA4358qhEEyRUUkmXjV4lCG1jBWXSG5/nfN83LjSKRKcALAmNW1DjkpWROyMzB7TOvq9Hnfn/5tehz2BPG1+zHYuV0lXZOk1Aqq9viK0Z36KYtt9RT1anKct+3pScKLxsADyLrPpV4HGCEWRI0rKVFJDqxDr8bNKkl0vDZqWBWeUAeG8zxuk/SQNcEyperSRkNJv7+HuoV2ESbG5kMRFPql3JVfkpND1vtWbpajHu0WJEDfPuCXPiILzMg/i9qQbRka/6FmqlxIaQ6LTdhs3QW06gD2Io8fQn3ktrWH6NaOTcBj7Ezs8QsrUktamPN0ButkT6Pr4UPqAAYZTFySVdSNScFkgA/xZTw4deCH38JIFcyI1yez90SJrmmPBbCHo1KGQBYnveeq7F02l0Vq/LefU1Jhn+bueiWZvAJeT3ttet7asxd3g/7kH8AYp7sT66x7ZL3gbxvpIIrWHo0q7tDyHUznwA==
  template:
    metadata:
      creationTimestamp: null
      name: os2iot-backend-encryption
      namespace: os2iot-backend
    type: Opaque
