---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-os2iot
  namespace: os2iot-backend
spec:
  encryptedData:
    password: AgBRlXVPHYcSJvA6pOF+CmQ7LcYXpCBG9rLxMXsT7slIJxAqb1VRgV6TtytfVnb3pIOnoBXjdvLWhg+97apOlkjeYKfsq05/LFOWbwqjndkL1Jug/KQVHpwa55H9GCT17GlOpDRn6Lp0GEzZFp09pWLly8gLmjXnxXqYirkUVGc7NqzuWKNpBPQnyVb+dCjDN0MhZ+fhPnPnHy0CzJKyc3tlM8jD3ml29I6kUPF6c2cvB3vWT4VOK8uGFiRIqv1IDszE8BbhIV+PLylHidNoq8WPqBpgmy/gF7ST1Ndv9saYda/QJg2Rut4a1IP/Uo1gqe2I0sN5LaC6azpmLJg6BkVrKXi72IOYvmA/EVREI0MpELZrdBCGVV2ydmi274HWUXYM8wVBBE5xI8fhnAFHah48oFE67IoN84xA1gFnb+mYXfadXQ7vkl9QSBA7h7E6WhUtMsmzF2K7UwdW2/I9nY6881uU0J4WxDjUl25DqlcdkzY6oSCUvTI4fIuwOYBOS0OEmRJYBm9bgmjkvfDrGBSIIk1UK79QFg+Nj+VbbhRDcmzcc9uefZxBIrHH7Z+wA1Zsq6ew+LL6Mfwsgnwe6UG3xbZleNUP6ttB9n1Pcx20VRlVR9Ipoug30PpZv9L2iKwCMXZihwQCuBVrsX6wzmVeAw6x+DOkmV9RiM1h5j4VX3IyaO+ruEo8c7b8ZzcVMYOUdmufDdqeq1DKBftpZxXe2lvZBfry4MzeddCGPQ+J0w==
    username: AgBi2cehNrnvhd757jEwqbtrjc6bCRlG70Sy9/d0n36bKhL+TKtxcOTWoU51Ts4P1mymi0Yr5QQi27/8Gy2vVdUrUw7SLQd840JWtX8yJ8PpYxhwL244F1eC0v/Uu6yYpNTTnRcaZYXMm8WJ1xids2983l6CyDwGg68SY7ZJGGdLL+aiGAAZVu45T1inOsWWHxJoOMeIA/6j+9L8KwQS7CKXF/T1sexMeoojufGCDOjfhejwArJBgn1B2ECRhVyGwlr7ymG+Y1QziSQ6s6O5geNbS4Wal/4XwyAF2RDtVwKiE+WUXA2ItrSDywFL3ZRRsVeEU9rjLXiAMGpwb2xO8jAKc9bmc+uNeTU1qmHKMvMaU7ji1HiZ+u2taFzw96RPESXywEEKPbRoeWpQN2p4B63jCKl83gMqfillK/vEez1xWMWZCoAwpka2GlNyx++zII3DfmW8/tEkzm7xoVwo7T0H6u/qSSPV7Zv4DTmUrlJGjcIne8ai2sLkVAoo2xS/K6/Fym7MlSVcyJxlzAZQxYT63/ibmgBktqho5NLNJMe6lM5yLKCuab5G5YN49B/7jTeGU6JN57UBWGfKxZRWazH17ciy3kQCsvIM6/a7ihk4ahpCwDmM+NX4o4kbn2kNLKdU9DGe6VJg1h4gAvaBahHhs5P0oIG9mKB6ZxEBEjoOaG5OzMWUNLtR1o7/XWOkAMzuvt75yGE=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-os2iot
      namespace: os2iot-backend
    type: Opaque
