---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-chirpstack
  namespace: chirpstack
spec:
  encryptedData:
    password: AgCSq7hgQjq1BGud9PSfPLrwdXLYJeGdR6GX5X0I2EbqoCMR2YFlDxLD5W5OIWTEJEXtWlEFYujYMZQzaeu1WMnkx3p5/hJwPSD6Qxhvb2VeO+jg+ulj9lsq7fxo1LrKgrOPnnMaz+nQAX4o4Bd3sP/W2oWP4UuKRrj7tgghcrSOsQZqSQRn5zjB4L8gKpnzjupmJeQEhHgpuKdVGUN+8Ajp6j7bAqo9Lj3B7z6DnbVjgmOQD7IaYzv+Q13l4dLp8mdLpl68u08C7X4W30rwD/MLiz9O7cWBEhaSETu4tA0nqurUPeOuANMupsKw4Iw1KYFtmxZV0Hc/HcipiJWwT5NxZIT5s4APGyUSd/eQ14KfzSPoXZrbY6CKOA6AvGsPl2mEShQadvsoIbjiiAZDU2FLhsJzakx6jNCmSrbDAUI7B6zMXo6iB+tTshwQbxjF7DVf4qyUxQeSmfTRZrnF/cO5AyIZEoNzaRwP4CrIItVeRBmK8WaU58Mz4LuB/J8DYMPa44wBf3eXM98h8/AZZAdvVlM/GvxFI8Rh/MuvYn1CCLSm7ikcvkdOBLTb8n9L0oTXPhAGtS2aKbtTwpL4qqHslBNLOlKJ1yH2pkFyo/geDyVhNe01Qi5zzJ3FRqXX5g/pLbeFevHZgq5qPyXfBSiOAco53RXt9x7deC36sNKETKZfxGujd03pFZ5RUxgE7Znhqwu3PqSWj3WJM8Ol8SiuoX8eW+eGUVcaIAwetSm4TA==
    username: AgDCYJoexMbJV32wyDprpI6v04+5a9Sx+x2ExV2Jtqu7OatfDvyn+DcplgZ3Tv7mrG6lys9Q6SIguQe3VkzKi9IL+m/TD4PazIc0+q0vXPcybXdKoNqI7SpRkiQMPkJhPP7e/AtsuOcjA3JmYeffQ6uBV49++fMum9ZE23El0tcRFyAsapJC/bGUXaPDAiM0nfpn+4uE6vB0uwCMF3WanOzRcJECV0/x/tkXXstxUfDELkQaZRYWorbnJFzGvJlYV/Y/ToeDYiaO3jHScRKCVDLePVSTn2Y0NpXfNDLbjt7NRAv+t8QmRa6GsP7+q/FIO2fJ8t0OCL+ZTnZTx9WsG/o/3gAgapi7pwXF6bh0MkvRnfgBKI/aIeo4MCovuMrKRvjTnZNysm/DiHrTzwiCqSlzEYuchyz0tmwAFXvG4Q0dW7C2WQ1Ge70eUVK8/XSNVToDVAbcwQpMxjNdkDTFDZe+GfWmP9MdLoOFOGRDh1p3h2Hws1nQtDScirzFsyhLNcfKE/UBx8IlqNzJjSqJ/2txk/Iu9efLoJZvdX0KilxF/oQ1xieEL/T1jZK3pUj5nLwYnGUN3Uz72jBYz95aH1aZaL+31djFYRcpv7lxCotOEKh15nj1wv/ZmegOaVvdUp5gF39czzF/PSVya39Nter66CTBy1EIIhv8ITqit5oKscwc5TI4NYtUXS1iXQ44hD9aa+RcR+vNmCIj
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-chirpstack
      namespace: chirpstack
    type: Opaque
