---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-cluster-chirpstack
  namespace: chirpstack
spec:
  encryptedData:
    password: AgClwfUH8TCAkNW/lKHbKU1rw2urSaStB/OhxefrytCNaY8eu68OGiA4Whw++mboOXRH9szICr8A9e4lRb5qhY38OEhDZpbUFoPxCZzgB0BpkC4z4zv2sElYq68Hk93nsjIBGSOHSA32dlqoOn9p4s7RN1ITJ90l6iUKHLZQuX4H82pGZA2fXCuLKdzszPiH5zJLCTLgVCG8Q77Rt8h7WBibkGFnlNRhTjol7ZcWExQJ+ezC28/E06Fbf2XtUjRjOMrjCtWkOIT50yFgL0KiBzUyAO5M0RkRPfIUzVBhVDhlYF704n1QCw0+DegCZ79Tt/Wql0E6c7iL1Ne6t0LGNypGZ+L0mFFltAPsEo0avZ52AdZUQelgDGHiiiFkT9kkyHX5/pflSlBYfg3VjRPDZft1PImQ9TW/2PAbDyCNZ4J2spJ802YvSjZqU/o7KEyIct5X6tF7FJdte2ubxrdSJ2sRX2vY+B2UQwmbon+7cHVxTlI0SCQeXZPtHWGnA1HfebVnI9ZidFYpPf6/ijjrGk3fFrIpOyGIs8AU/fkY8NAcvKj3jr+BbrIIGtqAKeFlIY+rOgNCNQa5Kg+QcUKNfIqjQiv5h6Aaamz0r8Wn5KMD4ZcX7QHia0bnxZzab3YPNv9UVcRPIaDVP9LErmTOlCW4eE/ImSLY3ey69mGGdeFjUoqcXEHQIh66w1ZRuJKiblN7Kd4AQgGNTDDZng8fFbUUwAuqU1uda0QRA6aHy3oavw==
    username: AgBWcH5spwLseAHeH9eanLOrKxp10qCcBBiT8X7guL6a7Wir+pW3T/0Y2P7Qf5tD5cRLg65W2K4+ZjpPPr6S0Mz+OACMd4TZPve0J4BfwUxivx82IDCxplPr5fuGYzgGDMKJGHx/ekZenEYroDUyIfEiRuSqMznzZHOKUNs395hflc9+m4nStTuwSi6ZuUOECWmcJ/VdLt3Y7AbbhLB74omQtqEp8eJb0c5jQnKouxlngaUWFXW+rOCysAtfKuUMZMrxJPKybfs/qH9abSluvrR+5rsijCQsU1fPwYMKOnXShO+44oBV4E8V6F83bP3qQ0ogJW+OaLdpwaXWM3sFRE7LMy5yjBGsYvlHDFrI9Zv609n1BE0N/ZO/TAIxZnh6k3gNuq/ZIs9SI7Sbfpun180AAvqn1TXCT4BBHLSEzNLIczBZrpW/Flu2H+0woHthCSfukSkwxqpbUt9ozIGSlCOxaRnsuwnm7Apo/onWVsGunV2joD58r1/dSe4oOVBaCIik+gwdsp+05wLHhEzQ11ITvgkiPVciw4C9dAzI25byPEsIBFI1R5gKwcCtX2m9R5YpCL8k/x0jzenm8iaQwlIctrWczmXKwaWcjA/C3UbeSmju+OoZhqfc68d5/cJ9opJb37PpQ6dmTGLU1BwVxWAKQy2w90UFv+cbDw6SLqst1pDooDL5pu+9lNoGGJT66ojlJ3XTsizJ60Sm
  template:
    metadata:
      creationTimestamp: null
      name: postgres-cluster-chirpstack
      namespace: chirpstack
    type: Opaque
