apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-claim-chirpstack
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
