---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-redis-config
  namespace: chirpstack
data:
  redis.conf: |
    maxmemory 128mb
    maxmemory-policy allkeys-lru
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: chirpstack-redis
  namespace: chirpstack
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: hcloud-volumes
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  redisConfig:
    additionalRedisConfig: chirpstack-redis-config