apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: chirpstack-redis
  namespace: chirpstack
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  redisConfig:
    maxmemory-policy: allkeys-lru
    maxmemory: 128mb