---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgDCGKbyDKWm+Kkxe87/QTwpP9q4ITVykS4PkwdOQdrxl+kI3jRnjSVyYSWMgRaF5etQ16ePSEMYBXIZXX4KPRON2/O8G7ImPrMs7LP7pN7WwrTlKweZGoHU3lQhyDIIoxkNqjyFjZLH8Va8lPPwNPtMSdNVoX7aFJ6fZ/lnRagYdzUp2O4Y2Dbey0qOVXd3QQzTb+P65GO7JRx/H/CfmFCyG5Kwzal5/lrzI/HDJ392XQLcHfpwV5pM14+S/zcJyZ1hfR6mKu4/KSnF0yyJqCXQUzXE0oBGogpNw/Lrqiy9BB9sqywjUENs1NbL7plwmLBPto1r0SINW/lFpcbjkfN7p0bHfr2cBuXFC4Qh6ALLqy6acYIcY2sW+ZFaGD9Sgdi34HaNam36WeDOWqiaGB4uOXi/2C49RerEJYwSAnDcMhqXhGIwpQTI0gswmYebCQutr8p4dhdvXxxc7/RiwCAi2Lw8M9ui12VFxIh7PLPe55jqyxs3o8uWD58N242L5xC4yQqHIcKJgUGbainzsuawrx5tzEHtn9sra4DNMg7iX7IxB6PoG13oBEIe7tR93NOuwzYizMiZ1ZN1j66ychE0U6J73OBsNJiCREzTUPmeLnUzOYjTVG1SfweAlqdlBjsSYAglH1/N45folWVktwzTfjZCc8b4Rxe2iNXsxqe0MPzo9esxL2X1/3MBWyFYBQkySpOGyf5LVRq4ZKN//U3jVFmFJ4gInN1MuTCnRTV0GqsWLsNeB+5iZ9C+ZfeaUiRa3Ow9ETReJm9XyRscpEHI
  template:
    metadata:
      creationTimestamp: null
      name: hcloud
      namespace: kube-system
    type: Opaque
